### ISSUE TITLE
Diff with superagent

### ISSUE THREAD

**Issue by webpro** [brandonjpierce/jax#1]
This lib is smaller than superagent, but what are the main differences? Or, are there any features missing compared to superagent?

**Comment by brandonjpierce** [comment]
@webpro there is not a huge difference between the two besides size and method names but Jax has stripped away some of the what I think were unnecessary methods from superagent such as auth() and accept(). The response object in Jax is also a little different in what it returns (see readme).

The whole goal of Jax was to have the same expressive syntax for creating AJAX calls that I have come to love about superagent in the tiniest file size possible without sacrificing features.

I also would like to eventually have promise support built in and get some feedback from users on things that would aid them when using Jax.

**Comment by webpro** [comment]
Thanks for your reply!

Perhaps good to note the diffs in the readme (and how to achieve the same with Jax).

Btw, imho, built-in promise support might be overkill, as promise libs usually have e.g. [promisification](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification) helpers (not sure how it would work with Jax API), and it would add to the (currently small) size significantly.

This actually brings me to the fact that I would prefer to have a regular callback mechanism (i.e. `Jax.get(url, callback)` so that it looks more familiar to most JS developers in general, and it can be easily promisified.

**Comment by brandonjpierce** [comment]
@webpro Good point on the promise helpers. 

I do like the Jax.get(url, callback) idea as well. Look for a update with this soon!

**Comment by brandonjpierce** [comment]
@webpro I added new syntax sugar for the HTTP verb methods so now `Jax.get(url, callback)` is possible. I also updated the README to include information when migrating from Superagent.

**Comment by webpro** [comment]
Thanks!
